// Tests are generated by codex
// Prompt: generate unit test for the functions in utils.ts and put them into a test file.

import { afterEach, describe, expect, it, vi } from 'vitest';

import { filterItems, isPartItem, loadJsonArray, moneyToNumber, normalize } from './utils';
import type { PartItem } from './types';

describe('isPartItem', () => {
  it('returns true for an object with a non-empty name', () => {
    expect(isPartItem({ name: 'Ryzen 7 7800X3D' })).toBe(true);
  });

  it('returns false for null, non-objects, and empty names', () => {
    expect(isPartItem(null)).toBe(false);
    expect(isPartItem('cpu')).toBe(false);
    expect(isPartItem({})).toBe(false);
    expect(isPartItem({ name: '' })).toBe(false);
  });
});

describe('moneyToNumber', () => {
  it('parses formatted dollar values', () => {
    expect(moneyToNumber('$1,500')).toBe(1500);
    expect(moneyToNumber(' 2,499.99 ')).toBe(2499.99);
  });

  it('returns null for blank, invalid, or negative input', () => {
    expect(moneyToNumber('')).toBeNull();
    expect(moneyToNumber('abc')).toBeNull();
    expect(moneyToNumber('-42')).toBeNull();
  });
});

describe('normalize', () => {
  it('trims and lowercases strings', () => {
    expect(normalize('  RTX 4080 SUPER  ')).toBe('rtx 4080 super');
  });
});

describe('loadJsonArray', () => {
  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('loads an array and filters out invalid part items', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn().mockResolvedValue({
        ok: true,
        json: async () => [
          { name: 'Corsair RM850e', wattage: 850 },
          { chipset: 'B650' },
          null,
        ],
      }),
    );

    await expect(loadJsonArray('/data/power-supply.json')).resolves.toEqual([
      { name: 'Corsair RM850e', wattage: 850 },
    ]);
  });

  it('throws when the response status is not ok', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn().mockResolvedValue({
        ok: false,
        status: 404,
      }),
    );

    await expect(loadJsonArray('/data/missing.json')).rejects.toThrow(
      'Failed to load /data/missing.json: 404',
    );
  });

  it('throws when the response body is not a JSON array', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn().mockResolvedValue({
        ok: true,
        json: async () => ({ name: 'Not an array' }),
      }),
    );

    await expect(loadJsonArray('/data/cpu.json')).rejects.toThrow(
      '/data/cpu.json must be a JSON array',
    );
  });
});

describe('filterItems', () => {
  const items: PartItem[] = [
    { name: 'ASUS Prime B650-Plus' },
    { name: 'MSI MAG B650 Tomahawk' },
    { name: 'Gigabyte B550 Aorus Elite' },
  ];

  it('returns an empty array when there is no open key or query', () => {
    expect(filterItems(items, null, 'b650')).toEqual([]);
    expect(filterItems(items, 'motherboard', '   ')).toEqual([]);
  });

  it('filters standard parts by name', () => {
    expect(filterItems(items, 'motherboard', 'B650')).toEqual([
      { label: 'ASUS Prime B650-Plus', value: 'ASUS Prime B650-Plus' },
      { label: 'MSI MAG B650 Tomahawk', value: 'MSI MAG B650 Tomahawk' },
    ]);
  });

  it('filters GPUs by name or chipset', () => {
    const gpuItems: PartItem[] = [
      { name: 'ASUS TUF Gaming', chipset: 'RTX 4070 Super' },
      { name: 'Sapphire Pulse', chipset: 'Radeon RX 7800 XT' },
      { name: 'Gigabyte Windforce' },
    ];

    expect(filterItems(gpuItems, 'gpu', '4070')).toEqual([
      {
        label: 'ASUS TUF Gaming 鈥?rtx 4070 super',
        value: 'ASUS TUF Gaming',
      },
    ]);

    expect(filterItems(gpuItems, 'gpu', 'gigabyte')).toEqual([
      {
        label: 'Gigabyte Windforce',
        value: 'Gigabyte Windforce',
      },
    ]);
  });

  it('caps the result set at 50 items', () => {
    const manyItems: PartItem[] = Array.from({ length: 60 }, (_, index) => ({
      name: `Case Fan ${index}`,
    }));

    expect(filterItems(manyItems, 'case', 'case fan')).toHaveLength(50);
  });
});
